### PR TITLE
add line numbers to print out

### PR DESCRIPTION
**Pull request by charliegallop**

### CODE REVIEW

**Review by MaxVanDijck — APPROVED** [review]
Beautiful stuff, idk if you get a badge though

**Comment by charliegallop** [comment]
@MaxVanDijck oh...can I unmerge this then?

**Comment by MaxVanDijck** [comment]
> @MaxVanDijck oh...can I unmerge this then?

Not really, I'd have to revert, whatsup

**Comment by charliegallop** [comment]
I just want my badge

**Pull request merged**
